### ISSUE TITLE
ModularInput.service() has authorize issue

### ISSUE THREAD

**Issue by oshulaev** [splunk/splunk-sdk-javascript#79] opened 2019-06-06 07:57 UTC
When i try using ModularInput.service() in my modular input, i get 401 status code.
'SessionKey' is not specified in created service.

_"splunk-sdk": "1.9.0"_

**Comment by fantavlik** [comment] 2019-06-10 20:10
Thanks @oshulaev we have added this to our backlog to investigate.

**Comment by ncanumalla-splunk** [comment] 2021-08-23 22:27
@oshulaev Please try the latest version of this SDK where this may be fixed. The current tests for this feature are executing successfully. Please provide any other steps to reproduce if this is still an issue.

**Comment by ncanumalla-splunk** [comment] 2021-08-31 17:09
Closing this issue due to no further response. Please try latest SDK version and reopen if issue happens.

**Closed by ncanumalla-splunk** 2021-08-31 17:09 UTC
Labels: awaiting response, auth
