### ISSUE TITLE
Problem with umlauts

### ISSUE THREAD

**Issue by kronsi** [splunk/splunk-sdk-javascript#36] opened 2015-03-31 21:55 UTC
Hi, 

if I log something with that sdk and that included german umlauts, than the signs will be cuted on the end, so I get invalid JSON on the SPLUNK Frontend. 

For Example:
var street = "Ummelner Straße 6";

the correct JSON variant is:
{ "street": "Ummelner Straße 6" }

I get that in SPLUNK that:
{ "street": "Ummelner Straße 6" 

-----------
Example 2 ( two umlauts ):
var street = "Ümmelner Straße 6";

the correct JSON variant is:
{ "street": "Ümmelner Straße 6" }

I get that in SPLUNK that:
{ "street": "Ümmelner Straße 6

I tast it the hole day, believe this is not a problem with utf8 :)

thanks for your support.

**Comment by shakeelmohamed** [comment] 2015-03-31 22:05
Hi @kronsi 

Thanks for letting us know, we will look into this

**Comment by glennblock** [comment] 2015-04-01 00:40
Thank you @kronsi. We'll definitely investigate!

**Comment by shakeelmohamed** [comment] 2015-04-01 02:11
@kronsi can you give us a code snippet that demonstrates this behavior? It would be great if we could also know which version of Splunk and which version of the SDK you're using.

**Comment by kronsi** [comment] 2015-04-01 05:34
Hi,

this is not a Problem :).. I use the current sdk version ( 1.7 I mean ). My Splunk Version is 6.2.1

Here you see a Mapquest Geo Reverse, that work with express and your log.js... the tclog object, log's to splunk...

geoReverseMapQuest : function( lat, long, res ){
		var location = new Object();
		location.latitude 	= lat;
		location.longitude 	= long;
		
		var mapQuest = "http://open.mapquestapi.com/geocoding/v1/reverse?key="+mapquestApiKey+"&location="+lat+"," + long;
		needle.get( mapQuest, function(err, resp, body){			
			var temp				= JSON.parse(body);
	
			if( temp.results[0].locations[0] ){
				temp				= temp.results[0].locations[0];
				location.street 	= c( temp.street );
				location.city 		= c( temp.adminArea5 );
				location.state 		= c( temp.adminArea3 );
				location.zipcode 	= c( temp.postalCode );
				location.country 	= c( temp.adminArea1 );
				
				
			}
						
			console.log( "mapquest location " + location.city );
			if( tclog != null )
				tclog.log( { provider: "mapquest", result: location, method : "georeverse" } );
			res.send( JSON.stringify(location) );
		});
	},

If you need a ApiKey, just ask an give me a private message possibility, please...

thanks.

**Comment by shakeelmohamed** [comment] 2015-04-01 22:49
FYI I'm able to reproduce this issue, we'll investigate a possible fix soon.

**Comment by shakeelmohamed** [comment] 2015-04-30 22:12
Hi @kronsi 

I've got an update for you. So it turns out the way we're calculating the `Content-Length` header doesn't take into account the byte-length of the string we're logging. Calling `"Ümmelner Straße 6".length` will return 17, but the byte length is actually 19 due to the 2 non-latin characters. 

We will have a fix out with the next release, thanks for your patience

**Comment by shakeelmohamed** [comment] 2015-05-06 20:46
Hi @kronsi 
We just released a fix for this as part of v1.7.1, please re-open this if you're still having issues.

Thanks again for reporting it!

**Closed by shakeelmohamed** 2015-05-06 20:46 UTC
